#!/usr/bin/env bash

set -euo pipefail

echo "~~~ Setup Pulumi"

PULUMI_VERSION="${BUILDKITE_PLUGIN_SETUP_PULUMI_VERSION:-$(curl --silent --show-error "https://www.pulumi.com/latest-version")}"

curl -fsSL https://get.pulumi.com | sh -s -- --version $PULUMI_VERSION

pulumi version

USE_OIDC="${BUILDKITE_PLUGIN_SETUP_PULUMI_USE_OIDC:-false}"
PULUMI_CLOUD_BACKEND_URL="https://api.pulumi.com"
BACKEND_URL="${BUILDKITE_PLUGIN_SETUP_PULUMI_BACKEND_URL:-$PULUMI_CLOUD_BACKEND_URL}

if [ "${USE_OIDC}" != "true" ] && [ -z "${PULUMI_ACCESS_TOKEN:-}" ] && [ "${BACKEND_URL}" = "${PULUMI_CLOUD_BACKEND_URL}" ]; then
    echo "❌ PULUMI_ACCESS_TOKEN is required for Pulumi Cloud backend since OIDC is not used."
    exit 1
if

OIDC_AUDIENCE = "${BUILDKITE_PLUGIN_SETUP_PULUMI_AUDIENCE:-}"

if [ "${USE_OIDC}" = "true] && [ -z "${OIDC_AUDIENCE:-}" ]; then
    echo "❌ audience is required when using OIDC auth method with Pulumi Cloud."
    exit 1
fi

bk_token=$(buildkite-agent oidc request-token --audience "$OIDC_AUDIENCE")

PULUMI_TOKEN_TYPE="${BUILDKITE_PLUGIN_SETUP_PULUMI_PULUMI_TOKEN_TYPE:-}"
PULUMI_TOKEN_SCOPE="${BUILDKITE_PLUGIN_SETUP_PULUMI_PULUMI_TOKEN_SCOPE:-}"

if [ -z "${PULUMI_TOKEN_TYPE:-}" ] || [ -z "${PULUMI_TOKEN_SCOPE:-}" ]; then
    echo "❌ pulumi-token-type and pulumi-token-scope are required when using OIDC auth method with Pulumi Cloud."
    exit 1
fi

pul_access_token=$(curl -X POST  \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d 'audience=urn:pulumi:org:test' \
        -d 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
        -d 'subject_token_type=urn:ietf:params:oauth:token-type:id_token' \
        -d 'requested_token_type=$PULUMI_TOKEN_TYPE' \
        -d 'scope=$PULUMI_TOKEN_SCOPE' \
        -d 'subject_token=$bk_token' \
        https://api.pulumi.com/api/oauth/token)

PULUMI_ACCESS_TOKEN=$pul_access_token pulumi login "${BACKEND_URL}"

echo "✔️ Logged into backend $BACKEND_URL..."
